version: '3.8'
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: log_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: logistics_secure_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    depends_on: [db]
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head && gunicorn app.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"

volumes:
  pgdata:
