"""Initial secure schema

Revision ID: 163c29d2df47
Revises: 
Create Date: 2026-06-01 09:59:31.217466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163c29d2df47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('clean_prompt', sa.Text(), nullable=False),
    sa.Column('clean_response', sa.Text(), nullable=False),
    sa.Column('vault_snapshot', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_table('cargo_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('cargo_details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cargo_orders_organization_id'), 'cargo_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cargo_orders_session_id'), 'cargo_orders', ['session_id'], unique=False)
    
    # Custom RLS Configuration
    op.execute("ALTER TABLE cargo_orders ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY cargo_orders_isolation_policy ON cargo_orders USING (organization_id = current_setting('app.current_organization_id', true));")
    
    op.execute("ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY audit_logs_isolation_policy ON audit_logs USING (organization_id = current_setting('app.current_organization_id', true));")
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cargo_orders_session_id'), table_name='cargo_orders')
    op.drop_index(op.f('ix_cargo_orders_organization_id'), table_name='cargo_orders')
    op.drop_table('cargo_orders')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
